{
 "title": "Alerts overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "alert status pie",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    status,\n    count() as count\nFROM\n(\n    SELECT\n        status.state as status,\n        fingerprint\n    FROM r0.alerts\n    WHERE\n        date >= toDate(1686684884)\n        AND status != ''\n    GROUP BY\n        status,\n        fingerprint\n)\nGROUP BY status"
    }
   ]
  },
  {
   "title": "Total # of unique firing alerts",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    count() as count\nFROM\n(\n    SELECT\n        labels.alertname,\n        fingerprint\n    FROM r0.alerts\n    WHERE\n        date >= toDate(1686684884)\n        AND status.state = 'firing'\n    GROUP BY\n        labels.alertname,\n        fingerprint\n)\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Total # of unique firing alerts",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfFifteenMinutes(timestamp) as t,\n    count() as count\nFROM r0.alerts\nWHERE\n    date >= toDate(1686684884)\n    AND status.state = 'firing'\nGROUP BY t\nORDER BY t"
    }
   ]
  },
  {
   "title": "Firing alerts by instance",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    labels.instance,\n    count() as count\nFROM\n(\n    SELECT\n        labels.instance,\n        status.state,\n        fingerprint\n    FROM r0.alerts\n    WHERE\n        date >= toDate(1686684884)\n        AND status.state = 'firing'\n        AND labels.instance != ''\n    GROUP BY\n        labels.instance,\n        status.state,\n        fingerprint\n)\nGROUP BY\n    status.state,\n    labels.instance\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Firing alerts by instance",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n    labels.instance,\n    count() as count\nFROM\n(\n    SELECT\n        labels.instance,\n        status.state,\n        fingerprint\n    FROM r0.alerts\n    WHERE\n        date >= toDate(1686684884)\n        AND status.state = 'firing'\n        AND labels.instance != ''\n    GROUP BY\n        labels.instance,\n        status.state,\n        fingerprint\n)\nGROUP BY\n    status.state,\n    labels.instance\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Firing alerts by instance",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT labels.alertname,\n       count() as count\n  FROM (\n        SELECT labels.alertname,\n               fingerprint\n          FROM r0.alerts\n         WHERE date >= toDate(1686684884)\n           AND status.state = 'firing'\n           AND annotations.dashboard = ''\n         GROUP BY labels.alertname,\n                  fingerprint\n       )\n GROUP BY \n          labels.alertname\n ORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Firing alerts by instance",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT labels.alertname,\n       count() as count\n  FROM (\n        SELECT labels.alertname,\n               fingerprint\n          FROM r0.alerts\n         WHERE date >= toDate(1686684884)\n           AND status.state = 'firing'\n           AND annotations.dashboard = ''\n         GROUP BY labels.alertname,\n                  fingerprint\n       )\n GROUP BY \n          labels.alertname\n ORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Alertnames with missing runbook",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT labels.alertname,\n       count() as count\n  FROM (\n        SELECT labels.alertname,\n               fingerprint\n          FROM r0.alerts\n         WHERE date >= toDate(1686684884)\n           AND status.state = 'firing'\n           AND annotations.link = ''\n         GROUP BY labels.alertname,\n                  fingerprint\n       )\n GROUP BY \n          labels.alertname\n ORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Instance status timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n    time,\n    labels.instance,\n    status.state,\n    count() as count\nFROM\n(\n    SELECT\n        toStartOfHour(timestamp) as time,\n        labels.instance,\n        status.state,\n        fingerprint\n    FROM r0.alerts\n    WHERE\n        date >= toDate(1686684884)\n        AND labels.instance != ''\n    GROUP BY\n        time,\n        status.state,\n        labels.instance,\n        fingerprint\n)\nGROUP BY\n    time,\n    status.state,\n    labels.instance\nORDER BY count DESC\nLIMIT 150"
    }
   ]
  }
 ]
}